id: ID8B17A28
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:25:40+00:00'
last_modified: '2022-06-08T16:48:32.607073+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20826
  title: ཐང་ཡིག་གསར་རྙིང་ལས་བྱུང་བའི་བོད་ཆེན་པོའི་སྲིད་ལུགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    580B:
      image_group_id: I1GS105585
      title: ''
      total_pages: 422
      order: 1
      base_file: 580B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
