id: P010687
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:19:55.125014
source_metadata:
  id: bdr:W20826
  title: ཐང་ཡིག་གསར་རྙིང་ལས་བྱུང་བའི་བོད་ཆེན་པོའི་སྲིད་ལུགས
  author: ''
  volumes:
    8d50f1b679764c2da57ce11e7651d961:
      image_group_id: I1GS105585
      title: ''
      volume_number: 1
      total_pages: 422
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
